# layer rule
layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:zoom,layer_name:rofi

# layout support:
# tile,scroller,grid,deck,monocle,center_tile,vertical_tile,vertical_scroller
tagrule=id:1,layout_name:canvas
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:scroller
tagrule=id:4,layout_name:scroller
tagrule=id:5,layout_name:scroller
tagrule=id:6,layout_name:scroller
tagrule=id:7,layout_name:scroller
tagrule=id:8,layout_name:scroller
tagrule=id:9,layout_name:scroller

# monitor rule
monitorrule=name:^HDMI-A-1$,width:1920,height:1080,refresh:60,x:0,y:0
monitorrule=name:^eDP-1$,width:1920,height:1080,refresh:60,x:1920,y:0

# window rules
windowrule=isOpenSilent:0,width:1920,height:1080
windowrule=isfloating:1,canvas_notile:1,width:960,height:540,appid:zen,title:^Picture-in-Picture$
