# Import config files
source=~/.config/mango/cfg/animation.conf
source=~/.config/mango/cfg/appearance.conf
source=~/.config/mango/cfg/binds.conf
source=~/.config/mango/cfg/layout.conf
source=~/.config/mango/cfg/misc.conf
source=~/.config/mango/cfg/overview.conf
source=~/.config/mango/cfg/rules.conf
source=~/.config/mango/cfg/windows_decor.conf
source=~/.config/mango/cfg/autostart.conf

# This sources the noctalia theme

source = /home/wang/.config/mango/noctalia.conf

