# Config location:
# ~/.config/mpd/mpd.conf

music_directory     "/media/disk/Music"
db_file             "/home/wang/.local/share/mpd/mpd.db"
state_file          "/home/wang/.local/share/mpd/mpdstate"
playlist_directory  "/media/disk/Music/Playlists"

auto_update         "yes"
bind_to_address     "127.0.0.1"
port                "6600"
restore_paused      "yes"

audio_output {
    type "pipewire"
    name "Pipewire Output"
  }

user                "wang"

